INSERT INTO Event (ModuleId, GoogleCalendarId, Name, Details, Starts, Ends)
SELECT 15138, 1, 'Event 1', 'Event 1 details', NOW(), DATE_ADD(NOW(), INTERVAL 2 HOUR)
UNION ALL
SELECT 15138, 2, 'Event 2', 'Event 2 details', NOW() + INTERVAL 2 HOUR, DATE_ADD(NOW(), INTERVAL 3 HOUR)
UNION ALL
SELECT 15138, 3, 'Event 3', 'Event 3 details', NOW() + INTERVAL 4 HOUR, DATE_ADD(NOW(), INTERVAL 5 HOUR)
UNION ALL
SELECT 15138, 4, 'Event 4', 'Event 4 details', NOW() + INTERVAL 6 HOUR, DATE_ADD(NOW(), INTERVAL 7 HOUR)
UNION ALL
SELECT 15138, 5, 'Event 5', 'Event 5 details', NOW() + INTERVAL 8 HOUR, DATE_ADD(NOW(), INTERVAL 9 HOUR)
UNION ALL
SELECT 15138, 6, 'Event 6', 'Event 6 details', NOW() + INTERVAL 10 HOUR, DATE_ADD(NOW(), INTERVAL 11 HOUR)
UNION ALL
SELECT 15138, 7, 'Event 7', 'Event 7 details', NOW() + INTERVAL 12 HOUR, DATE_ADD(NOW(), INTERVAL 13 HOUR)
UNION ALL
SELECT 15138, 8, 'Event 8', 'Event 8 details', NOW() + INTERVAL 14 HOUR, DATE_ADD(NOW(), INTERVAL 15 HOUR)
UNION ALL
SELECT 15138, 9, 'Event 9', 'Event 9 details', NOW() + INTERVAL 16 HOUR, DATE_ADD(NOW(), INTERVAL 17 HOUR)
UNION ALL
SELECT 15138, 10, 'Event 10', 'Event 10 details', NOW() + INTERVAL 18 HOUR, DATE_ADD(NOW(), INTERVAL 19 HOUR);